consumer:
  msg:
    isMongodbCompatible: true
encryption: 
  msg: 
    topic: ~
endpoints:
  health:
    sensitive: false    
  shutdown:
    enabled: true    
    sensitive: false
feign:
  hystrix:
    enabled: false
  compression:
    request:
      enabled: false
    response:
      enabled: false  
management:
  security:
    enabled: false
mongodb: 
  msg: 
    isEnable: false
#mq:
#  consumeFromWhere: CONSUME_FROM_LAST_OFFSET
#  consumeMessageBatchMaxSize: 1
#  namesrvAddr: "10.88.26.79:9876"
#  producerGroup: pp-producer-group
#  threadMax: 20
#  threadMin: 10
producer:
  msg:
    producerCompatible: true  
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000    
security:
  basic:
    enabled: false 
spring: 
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
transaction: 
  isEnable: true
  topic: 1   
zk: 
  connection: 
    timeout: 30000
  host: "zookeeper01.scm.test.yonghui.cn:2181,zookeeper02.scm.test.yonghui.cn:2181,zookeeper03.scm.test.yonghui.cn:2181"
  mqservice: 
    subscription: 0
  session: 
    timeout: 30000
    
---
#svc-gov-sdk:
#  app-id: saas-sit
#  app-secret: 12345678
#  api-gateway-url: http://sit-api-base.yonghui.cn/api

#svc-gov-sdk:
#  appKey: pg-app-demo2
svc-gov-sdk:
  appKey: pg-app-demo3
  secret: 12345678
  gateway: http://sit-api-base.yonghui.cn/api
#  retry:
#    dbType: mysql
#    sharding-enabled: false
#    sharding-column: db_tag
#sdk-demo:
#  sdk-enabled: true
#  app-id: pg-app-demo1
#  app-secret: 12345678
#  server:
#    host: localhost-1
#    ip: 10.0.0.1
#  chain:
#    next:
#      app-id: pg-app-demo2
#      msg-type:
#      service: app-yh-svc-gov-sdk-demo-${spring.profiles.active}-${sdk-demo.chain.next.app-id}
#    node:
#      name: ${sdk-demo.app-id}-node1
#  api-gateway:
#    url: http://sit-api-base.yonghui.cn/api
server:
  port: 9001

spring:
  datasource:
    dbcp2:
      connection-properties: characterEncoding=utf8
      initial-size: 5
      max-total: 50
      max-wait-millis: 10000
      validation-query: "SELECT 1"
    type: org.apache.commons.dbcp2.BasicDataSource
    url: "jdbc:mysql://10.251.64.63:3306/db_retry_service_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true"
    username: bff_user_dev
    password: bff_user_dev@2021


hystrix:
  threadpool:
    default:
      coreSize: 1024 #并发执行的最大线程数，默认10
      maxQueueSize: 10000 #BlockingQueue的最大队列数，默认值-1
      queueSizeRejectionThreshold: 8000 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5   
 
log: 
  service: 
    secret: ec865a850d20db45
    ip: 
      address: http://api-base.cloud.bz/api/log
    customer: 
      code: test_log